config/routes.rb
Foodstreet::Application.routes.draw do
  root :to => "home#index"
  match '/d/' => "home#show", :as => :dashboard_show

  devise_for :users, :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, :skip => [:sessions]

  devise_scope :user do
    get '/signup' => 'users/registrations#new', as: :new_user_registration
    get '/logout' => 'users/sessions#logout', as: :destroy_user_session
    post '/login' => 'users/sessions#create', :as => :user_session
    get '/login' => 'users/sessions#new', :as => :new_user_session
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get '/current_user/update_dashboard' => 'photos#update_dashboard', :as => :update_dashboard

  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'you'
      get 'search'
    end
    member do
      get 'revoke_twitter'
    end
  end
  
  resource :follow, only: [] do
    collection do
      get 'following'
      get 'follower'
    end
  end

  resource :search, only: [] do
    collection do
      get 'username'
    end
  end

  #resources :notifications, :only => [:index]
  resources :photos do
    collection do
      get "albums"
    end
  end
  
  resources :outlets do
    collection do
      get 'featured'
      get 'promotion'
    end
  end
  resource :follow, only: [:create, :destroy]
  resource :like,   only: [:create, :destroy]
  resources :comments, only: [:create, :destroy, :index]

  resources :conversations do
    member do
      get 'recipient'
    end
    collection do
      get 'read'
    end
  end

  resources :search do
    collection do
      get 'tags'
      get 'locations'
    end
  end

  resources :feed, only: [:index]

  # devise_scope :user do
  namespace :ios, :defaults => {:format => 'json'} do
    namespace :api do
      resources :users, :only => [:create, :new] do
        collection do
          post 'login'
          get 'test'
          get 'logout'
        end
      end
      resources :fb_connects, :only => [:create]
      resources :posts, :only => [:create, :destroy, :update] do
        member do
          post 'reshare'
          post 'repin'
        end
      end
      resources :feeds, :only => [:index]
      resources :likes, :only => [:create]
      resources :comments, :only => [:create]
    end
  end
  # end

  match 'invites/email_form' => 'invites#email_form', :as => :invite_email
  match 'invites/:provider' => 'invites#provider', :as => :provider_invite
  match 'invites/:provider/loads' => 'invites#loads', :as => :invite_loads

  match 'contacts/:importer/callback' => 'contacts#callback', :as => :contacts_callback
  match 'contacts/:importer/disconnect' => 'contacts#disconnect', :as => :contacts_disconnect
  match 'contacts/invite' => 'contacts#invite', :as => :contacts_invite

  match 'posts/last_since/:id' => 'posts#last_since', :as => :posts_last_since
  match 'post/:id' => 'posts#show', :as => :single_post
  match ':slug/albums/:tag' => 'photos#index', :as => :photos_album
  match ':slug/albums/:tag/remove' => 'photos#remove_album', :as => :remove_photos_album
  match ':slug/albums/:tag/update' => 'photos#update_album_name', :as => :update_photos_album
  #   match ':slug/followers' => 'follows#follower', :as => :follower_of
  #   match ':slug/following' => 'follows#following', :as => :followig_to
  match 'inbox' => 'conversations#index', :as => :inbox
  match ':slug/photos' => 'photos#photos', :as => :user_photos

  namespace :admin do
    resources :users do
      collection do
        post 'manage_status'
      end
    end
    resources :posts
    resources :badges
  end

  scope :module => 'v2', :as => 'v2' do #;for future switch; to maintain same name helper, controllers but with root path
    resource :account, :only => [:show, :update] do
      collection do
        get 'revoke_twitter'
      end
    end
    resources :notifications, :only => [:index] do
      collection do
        get 'list'
      end
    end
    resources :activities, :only => [:index]
  end

  # scope :module => 'v2', :as => 'v2' do #;for future switch; to maintain same name helper, controllers but with root path
  namespace :v2 do
    root :to => "home#show"
    resource :comments, only: [:create, :destroy, :index]
    resources :feeds, :only => [:index]
    resources :posts do
      collection do
        get 'tagged_with/:tag' => 'posts#tagged_with', :as => :tagged_with
      end
    end
    resources :food_tags, :only => [:index]
    match ':slug' => 'users#show'
    match ':slug/invitation' => 'users#invitation', :as => "user_invitation"
  end

  resources :tag_subscriptions, :only => [:create, :destroy, :update]

  # Foodpedia and Post related

  match '/posts/tagged_with' => 'posts#tagged_with', as: :posts_tagged_with
  resources :posts do
    collection do
      get 'others'
    end
    member do
      post 'reshare'
      match 'repin'
      match 'flag'
      match 'promote'
    end
  end
  resources :pictures
  resources :foods
  resource :account

  # Any other URL is used like the user home page
  match ':slug', :controller=>"v2/users", :action=>"show", :as => :slug
  match ':slug/activities', :controller=>"v2/users", :action=>"activities", :as => :user_activities
  match ':slug/about', :controller=>"v2/users", :action=>"about", :as => :user_about
  match ':slug/subscriptions', :controller=>"v2/users", :action=>"subscriptions", :as => :user_subscriptions
  match ':slug/badges', :controller=>"v2/users", :action=>"badges", :as => :user_badges
  match ':slug/followers', :controller=>"v2/users", :action=>"followers", :as => :user_followers
  match ':slug/following', :controller=>"v2/users", :action=>"following", :as => :user_following
  match 'albums/search' => "albums#search"
  match 'location/search/:lat/:long' => "locations#search", :constraints => {:lat => /-?[0-9]+(\.[0-9]+)?/, :long => /-?[0-9]+(\.[0-9]+)?/}
  match 'current_user/update_album_position' => 'photos#update_album_position'

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  helper_method :sort_direction
  
  def index
    @flags = if (sort_direction == 'desc')
      Flag.desc(params[:sort] || 'id').page(params[:page])
    else
      Flag.asc(params[:sort] || 'id').page(params[:page])
    end
  end
  
  private
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/ios/api/posts_controller.rb
class Ios::Api::PostsController < Ios::Api::ApplicationController
  before_filter :find_post, :only => [:destroy, :update, :reshare, :repin]
  
  def create
    post = current_user.posts.new(params[:post])
    if post.save
      timeline = Timeline.add_post(current_user, post)
      render_for_api :api_all_feeds, :json => timeline, :meta => {:error => false}, :root => :post
    else
      render :json => {:error => post.errors.full_messages.join(", ")}
    end
  end
  
  def destroy
    if @post.destroy
      render :json => {:error => false}
    else
      render :json => {:error => @post.errors.full_messages.join(", ")}
    end
  end
  
  def update
    if params[:post].blank?
      render :json => {:error => 'Missing post new attributes'}
    elsif @post.update_attributes(params[:post])
      render :json => {:error => false}
    else
      render :json => {:error => @post.errors.full_messages.join(", ")}
    end
  end
  
  def reshare
    current_user.reshare(@post)
    render :json => {:error => false}
  end
  
  def repin
    album_tag = params[:post].delete(:album_tag_list)
    @repinned_post = current_user.posts.new({:message => params[:post][:message], :post_to_facebook => params[:post][:post_to_facebook], :post_to_twitter => params[:post][:post_to_twitter]})
    @repinned_post.message += " (#{album_tag})" if !album_tag.blank?
    @repinned_post.image = @post.image
    @repinned_post.repinned_post = @post
    if @repinned_post.save
      timeline = Timeline.add_post(current_user, @repinned_post)
      render_for_api :api_all_feeds, :json => timeline, :meta => {:error => false}, :root => :repinned_post
    else
      render :json => {:error => @repinned_post.errors.full_messages.join(", ")}
    end
  end
  
  protected  
  def find_post
    @post = Post.where(:_id => params[:id]).first
    render :json => {:error => 'Post not found'} unless @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  inherit_resources

  actions :create

  before_filter :find_post, :only => [:destroy, :update, :reshare, :repin, :flag, :promote]

  def index
    page = 1
    if !params[:page].nil?
      page = Integer(params[:page].to_s)
    end
    
    sorted =  current_user.feeds.sort_by { |obj| obj.created_at }
    
    
    feeds = Kaminari.paginate_array(sorted.reverse).page(page).per(10)   
    render_for_api :all_feeds, json: feeds, status: 200
  end

  def show
    post = Post.find(params[:id])
    @post = post
    respond_to do |format|
      format.json { render_for_api :post, json: post, status: 200 }
      format.html { render :show, :layout => 'photo' }
    end
  end
  
  def last_since
    id = params[:id]
    
    newfeeds = []

    sorted =  current_user.feeds.sort_by { |obj| obj.created_at }
    found = false
    sorted.reverse.each do |feed|

      if (!feed.subject.id.to_s.eql?(id.to_s))
        newfeeds.push(feed)
      else
        found = true;
        break
      end
    end
    
    if !found
      newfeeds = []
    end
      
    render_for_api :all_feeds, json: newfeeds, status: 200
    #render :json => {:error=> '', :feeds=> newfeeds }
  end

  def new
  end

  #
  #def create
  #  post = Post.new params["post"]
  #  post.user_id = current_user.id
  #  tag_list = params["post"]["album_tag_list"].split(",")
  #
  #  tag_list.each do |tag|
  #    tag_existance = Tagposition.where(:user_id => current_user.username, :tag_name => tag)
  #    unless tag_existance.any?
  #      #new_position = Tagposition.where(:user_id => "almazom").map(&:position).max
  #      Tagposition.create!(:user_id => current_user.username, :tag_name => tag, :position => 500)
  #    end
  #  end
  #
  #  if params["post"]["album_tag_list"].length > 3
  #    post.tags = params["post"]["album_tag_list"]
  #  else
  #    post.tags = "default"
  #  end
  #
  #  if post.save
  #    render_for_api :default, json: post
  #  else
  #    render json: resource.errors, status: :unprocessable_entity
  #  end
  #
  #end
  #


  def create

    #raise params.to_json

    post = Post.new params["post"]
    post.user_id = current_user.id
    post[:album_tag_list] = []
    # Search the album, if don't exist, we create it

    album_names_list = []
    
    if !params["post"]["album_tag_list"].nil?
      album_names_list = params["post"]["album_tag_list"].split(",")
    end
    

    #if album_names_list.length < 1
    #  album_names_list = "default"
    #end

    if post.save
      if params["post"]["album_tag_list"].present? && album_names_list.length > 0


        album_names_list.each do |album_name|
          album = Album.where(:name => clear_slug(album_name), :user_id => current_user.id).first

          if album.blank?
            #  create new album and Albumposition
            new_album = current_user.albums.new
            new_album.name = album_name

            if new_album.save
              #position of new album

              #user = current_user.username
              begin
                last_position = Albumposition.where(:user_id => current_user.id) ? (Albumposition.where(:user_id => current_user.id).map(&:position).max)+1 : 0
              rescue NoMethodError
                last_position = 0
              end

              p ap = Albumposition.new
              p ap.user = current_user
              p ap.album = new_album
              p ap.position = last_position
              unless ap.save
                render :js => "alert('error saving')" and return
              end

              #add post to album
              post.albums << new_album
            else
              logger.debug("can not save")
            end

          else
            #no need to create ALBUM
            album.posts << post
          end
        end
      else
        default_album = current_user.albums.where(:name => "Default").first

        if default_album
          #raise "default exists"
          default_album.posts << post

        else

          new_default_album = current_user.albums.create!(:name => "Default")

          ap = Albumposition.new
          ap.user = current_user
          p ap.album = new_default_album
          p ap.position = 500
          ap.save

          new_default_album.posts << post
        end
      end


      # TODO: Add "With who"
      params[:shared_users].split(',').each do |user_slug|
        if current_user.slug != user_slug.strip # Only we can share with non-current user
          user = User.find_by_slug user_slug.strip
          if not user.nil? # Only add non-nil users
            post.shared_users << user
            # Now we notificate to the user
            notificatioin = Notification.new(:event_type => 'being_tagged', :subject => post)
            notificatioin.save
            puts "==========> #{user.class} -- #{post.class}"
            user.notifications << notificatioin
          end
        end
      end

      # At Where
      location = Location.where(:name => params[:location]).first
      if location.nil?
        location = Location.new :name => params[:location]
        location.save
      end
      
      
      post.location_id = location.id if not location.nil?
      post.save
      
      render_for_api :default, json: post
    else
      begin
        render json: resource.errors, status: :unprocessable_entity
      rescue Mongoid::Errors::InvalidFind
        render :js => "alert('Error, can not add post!')"
      end

    end #post.save


#if post.save
#  # Now, if the user want to share with facebook or twitter, we do it
#  if params[:share_facebook].to_i == 1
#    current_user.publish_to_facebook(post)
#  end
#  if params[:share_twitter].to_i == 1
#    current_user.publish_to_twitter(post)
#  end
#
#  if album
#    #position of new album
#    user = current_user.username
#
#    album_exist_check = Albumposition.where(:user_id => user, :album_id => album.id)
#    unless album_exist_check.any?
#      last_position = Albumposition.where(:user => user).any? ? (Albumposition.where(:user => user).map(&:position).max)+1 : 0
#      Albumposition.create!(:user_id => user, :album_id => album.id, :position => last_position)
#    end
#  end
#
#
#  render_for_api :default, json: post
#else
#  render json: resource.errors, status: :unprocessable_entity
#end

  end

  def others
    user = User.find_by_slug(params[:slug])
    feeds = user.feeds.desc(:created_at).all.reverse

    render_for_api :all_feeds, json: feeds, status: 200
  end

  def destroy
    @post.destroy
    render :json => @post
  end

  def update
    params[:post].delete(:comments)
    @post.update_attributes(params[:post])
    render_for_api :post_feed, json: @post, status: 200
  end

  def tagged_with
    posts = Post.tagged_with(params[:tag].gsub('-', ' '), :on => 'food')
    render_for_api :all_posts, json: posts, status: 200
  end

  def reshare
    if current_user.reshare(@post)
      head :created
    else
      head :bad_requests
    end
  end


  
  
  def repin
    if request.get?
      @post.message = ''
      render :layout => false
    else
      @oldpost = Post.find(params[:post][:id])
      
      if params[:select_album_flag].to_s.eql? 'true'
        album_tag = params[:post][:album_tag_list]
      
      else
        new_album = current_user.albums.new
        new_album.name = params[:new_album]

        new_album.save
        album_tag = new_album.name
      end
      @repinned_post = current_user.posts.new(params[:post])
      @repinned_post.message += " (#{album_tag})" if !album_tag.blank?
      @repinned_post.picture = @oldpost.picture
      @repinned_post.food_names = @oldpost.food_names
      @repinned_post.repinned_post = @oldpost
      if @repinned_post.save
        Timeline.add_post(current_user, @repinned_post)
      end
      
      render :template => '/posts/repin_post'
    end
  end

  def flag
    if request.get?
      @flag = @post.flags.new
      render :layout => false
    else
      @flag = @post.flags.new(params[:flag])
      @flag.user_id = current_user.id
      @flag.save
      render :template => '/posts/flag_post'
    end
  end

  def promote
    if current_user.promote!(@post)
      head :created
    else
      head :bad_requests
    end
  end

  protected

  def find_post
    @post = Post.find(params[:id])
  end

  def begin_of_association_chain
    current_user
  end
end

app/controllers/v2/posts_controller.rb
class V2::PostsController < V2::ApplicationController
  def new
    render :layout => false
  end
  
  def tagged_with
    @posts = Post.tagged_with(params[:tag].gsub('-', ' '), :on => 'food').desc('created_at').page(params[:page]).per(10)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/v2/posts_helper.rb
module V2::PostsHelper
end

app/views/posts/_item.html.slim
li.post data-id=item.id
  .image = image_tag item.medium_image
  ul.statistics
    li.likes
      i.post_like
      span.count = item.like_count
    li.comments
      i.post_comment
      span.count = item.comment_count
    li
      i.post_share
      span.count = item.reshare_count
    li.repins
      i.post_pin
      span.count = item.repin_count

app/views/posts/_new.html.haml
#new_post.modal.hide.fade
  .modal-header
    %button.close{"type" => "button", "data-dismiss" => "modal"} &times;
    //TODO Hi {username}! Share some great food!
    %h3 Share some great food!
  .modal-body
    #picture_uploader
      %span.btn.btn-success.fileinput-button
        %i.camera
        %span Add Food Photo
        = file_field_tag "picture[file]", "data-url" => pictures_path(format: 'json'), class: 'file-field'
      .preview
        %img
      .progress-bar
        .progress.progress-success.progress-striped.active.fade
          .bar { style: "width:0%;" }
    = form_for Post.new, html: { id: 'new_post_form', class: 'new_post_from' } do |f|
      .hidden-input= f.hidden_field :picture_id
      %input.hidden-input{ :type => "hidden", :name => "user_slug", :value => "#{current_user.try(:slug)}" }
      %ul#postInfo.unstyled
        %li.clearfix
          %span.icn-tags.icns
          %span.inputWrap
            %label Food name
            .input-box= f.text_field :food_names, placeholder: "Add food name"
        %li.collapse.postToggle.clearfix
          %span.icn-albums.icns
          // %span.inputWrap= f.collection_select :album_id, current_user.try(:albums) || [], :id, :name
          %span.inputWrap.choose-album-wrap
            %label Albums
            %input{"id" => "post_album_id","type" => "text", "placeholder" => "Choose album", "name" => "post[album_tag_list]"}
            %span.post-album-arrow
            // %a{"id" => "post_album_add_button"} Add
          %span.inputRight (Optional)
        %li.collapse.postToggle.clearfix
          %span.icn-people.icns
          %span.inputWrap
            %label With who?
            %input{"id" => "posts_user_names", "name" => "shared_users", "type" => "text", "placeholder" => "Add users", "placeholder" => "Add user"}
          %span.inputRight (Optional)
        %li.collapse.postToggle.clearfix
          %span.icn-location.icns
          %span.inputWrap
            %label At where?
            %input{"name" => "location", "type" => "text", "placeholder" => "Add location"}
          %span.inputRight (Optional)
        %li.collapse.postToggle.clearfix
          %span.icn-comment.icns
          %span.inputWrap
            %label Add comments
            = f.text_field "message", placeholder: "Add comment"
          %span.inputRight (Optional)
        %li.collapseAction.clearfix
          %a{"data-toggle" => "collapse", "href" => "#", "data-target" => ".postToggle"} Add more info <small>(Optional)</small>
        %input.hidden-input{ :id => 'share_facebook', :type => "hidden", :name => "share_facebook", :value => "" }
        %input.hidden-input{ :id => 'share_twitter', :type => "hidden", :name => "share_twitter", :value => "" }

  .modal-footer
    == Share with friends at
    %a.btn.btn-large.btn-facebook Facebook
    %a.btn.btn-large.btn-twitter Twitter
    %a.btn.btn-large.btn-danger#new_post_submit Post

.modal-choose-album
  %ul.albums
    - current_user.albums.each do |album|
      %li.album= album.name
    - end if not current_user.nil?
  .actions
    %input.name{"type" => "text", "placeholder" => "New album"}
    %button.create
      Create

app/views/posts/create.html.haml
-#:javascript
-#  window.parent.addPost(#{ @post.to_json(only: [:_id, :message, :created_at, :like_count, :comment_count], methods: [:image_200, :username, :image_68, :created_at_time, :like, :all_taggings, :creator_slug])});

app/views/posts/flag.html.erb
<div>
  <ul>
    <%= form_for @flag, :url => flag_post_path(@post), :html => {:remote => true, :method => :post, :class => 'flag_post'} do |form| %>
      <div class="flag_post_errors"></div>
      <li>
        
        <%= form.radio_button :reason, Flag::REASON[0], :class=> 'reason_radio'%><%= form.label 'Spam', :class=>'flag_radio_label'%><br />
        <%= form.radio_button :reason, Flag::REASON[1], :class=> 'reason_radio' %><%= form.label 'Inappropiate', :class=>'flag_radio_label' %><br />

      </li>
      <li class="flag_description">
        <%= form.text_field :description, :class=>"flag_description_input", :placeholder=>'Please specify' %>
      </li>

      <div class="center">
      	<%= form.submit 'Flag' %>
      </div>
      
    <% end %>
  </ul>
</div>

<script type="text/javascript">
  //<!CDATA[
  $(document).ready(function() {
  	$(".flag_description_input").attr("disabled", "disabled");
    $('.flag_post').submit(function(){
       var submitButton = $('.flag_post').find("input[type='submit']");
       $(submitButton).attr("value", "Please Wait...");
       $(submitButton).attr("disabled", "true");
    })
    
    $(".reason_radio").change(function(){
    	
    	var value = $(this).val();
    	if (value == 'Incorrect Content'){
    		$(".flag_description_input").removeAttr("disabled"); 
	        
	      } else {
	        $(".flag_description_input").attr('disabled', "disabled");
	      }
    });
    /*
    $("#flag_reason").change(function() {          
      var value = $("#flag_reason option:selected").val();
      if (value == 'Incorrect Content'){
        $(".flag_description").removeClass('hidden');
        $.fn.colorbox.resize();
      } else {
        $(".flag_description").addClass('hidden');
      }
    });*/
  })
  //]]>
</script>

app/views/posts/flag_post.js.erb
if (<%= @flag.errors.blank? %> == true) {
  var id = "<%= @post.id.to_s %>";
  $("#"+id+" a.post_flag").text("Flagged").removeClass('post_flag').addClass('disable_post_flag');
} else {
  $(".flag_post_errors").html("<%= @flag.errors.full_messages.join(', ') %>");
  var submitButton = $('.flag_post').find("input[type='submit']");
  $(submitButton).attr("value", "Flag");
  $(submitButton).attr("disabled", false);
}

app/views/posts/new.html.haml
= form_for Post.new, url: posts_path do |f|
  .barrier_10.border_bottom.relative
    = f.text_field :food, :value => "Share new food...", :class => "wide_input inline"
    .post_error.animated.bounce Tell us something!
    .clearfix
    .post_image_cage
      .label_medium Upload a photo
      = f.file_field :image, :class => "inline"
  .barrier
    %span.extension.left
      %span.people
      %span.tags
      %span.place
    = f.label :tags
    = f.text_field :tags, :value => ''
    %span.right.relative
      = f.submit "Post", :class => "post_button button_gray"
      .post_loading
        %img{:src=> "/assets/loading-reply.gif", :alt => ""}
    .clearfix

app/views/posts/repin.html.erb
<div class="stream_item relative">
  <ul class="news_pane inline top">
    <%= form_for @post, :url => repin_post_path(@post), :html => {:remote => true, :method => :post} do |form| %>
      <div class="repin_post_errors"></div>
      <div class="repin_post_info"></div>
      <%= form.hidden_field :id%>
      <ul>
      <% current_user.albums.each do |album| %>
      	<li class="album_repin"><%= album.name %></li>
      <% end %>
      </ul>
      
      <%= form.hidden_field :message %>
      <%= form.hidden_field :album_tag_list %>
      <%= hidden_field_tag :select_album_flag %>
      
      <%= text_field_tag :new_album, nil, :class => "inline" %>
      <%= form.submit 'Create', :class=>'repin_submit' %>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
  //<!CDATA[
  $(document).ready(function() {
  	$("#select_album_flag").val("false");
  	$('.album_repin').click(function(){
  		$("#select_album_flag").val("true");
  		$("#post_album_tag_list").val($(this).html());
  		var submitButton = $('.repin_container').find("input[type='submit']");
  		$(submitButton).attr("value", "Please Wait...");
       	$(submitButton).attr("disabled", "true");
       	
       	$(".edit_post",".repin_container").submit();
  	});
  	
    $('.edit_post').submit(function(){
       var submitButton = $('.edit_post').find("input[type='submit']");
       
    })
  })
  //]]>
</script>

app/views/posts/repin_post.js.erb
$('.repin_container').find("input[type='submit']").attr("value", "Create");
$('.repin_container').find("input[type='submit']").removeAttr("disabled");
$('.repin_container').find("#select_album_flag").val("false");
  
if (<%= @repinned_post.errors.blank? %> == true) {
  var id = "<%= @post.id.to_s %>";
  $(".repin_post_info").html("Post repinned");
  var repinholder = $(".repin_container").parent().find(".post_repin");
  repinholder.html((parseInt(repinholder.html()) + 1));
  
} else {
  $(".repin_post_errors").html("<%= @repinned_post.errors.full_messages.join(', ') %>");
  var submitButton = $('.edit_post').find("input[type='submit']");
  $(submitButton).attr("value", "Pin It");
  $(submitButton).attr("disabled", false);
}